Website = "https://patenaude.io/"

[Details]
Icon = "icon.png"
Name = "NHWatcher"
ID = "io.patenaude.nhwatcher"
Version = "0.2.5"
Build = 0

[LinuxAndBSD]
GenericName = "Nethack watching screensaver"
Categories = ["Screensaver"]
Comment = "Watch games on NAO"
Keywords = ["screensaver"]
